package edu.cwru.yxs626.typeinference;

/**
 * A MissingTypeEntryException is thrown when a given TypeEntry is not in the
 * TypeSystem.
 * 
 * @author Yue Shu
 */
public final class MissingTypeEntryException extends Exception {

    /** The Serial Version UID auto-generated by the IDE. */
    private static final long serialVersionUID = 1795089750842043370L;

    /** The TypeEntry related to the MissingTypeEntryException. */
    private final TypeEntry typeEntry;

    /** The TypeSystem related to the MissingTypeEntryException. */
    private final TypeSystem typeSystem;

    /**
     * Creates a new MissingTypeEntryException.
     * 
     * @param typeEntry  the TypeEntry related to the MissingTypeEntryException
     * @param typeSystem the TypeSystem related to the MissingTypeEntryException
     */
    public MissingTypeEntryException(TypeEntry typeEntry, TypeSystem typeSystem) {
        this.typeEntry = typeEntry;
        this.typeSystem = typeSystem;
    }

    /**
     * Returns the TypeEntry related to the MissingTypeEntryException.
     * 
     * @return the TypeEntry related to the MissingTypeEntryException
     */
    public TypeEntry getTypeEntry() {
        return this.typeEntry;
    }

    /**
     * Returns the TypeSystem related to the MissingTypeEntryException.
     * 
     * @return the TypeSystem related to the MissingTypeEntryException
     */
    public TypeSystem getTypeSystem() {
        return this.typeSystem;
    }
}